CREATE DATABASE questionSprinter;

USE questionSprinter;

CREATE TABLE Teachers (
	ID INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	passwrd VARCHAR(200) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Exams (
	ID INT NOT NULL AUTO_INCREMENT,
	teacher_ID INT NOT NULL,
	name VARCHAR(50) NOT NULL,
	examKey VARCHAR(10) NOT NULL,
	FOREIGN KEY (teacher_ID) REFERENCES Teachers(ID),
	PRIMARY KEY (ID)
);

CREATE TABLE Questions (
	ID INT NOT NULL AUTO_INCREMENT,
	exam_ID INT NOT NULL,
	question VARCHAR(300) NOT NULL,
	answer VARCHAR(300) NOT NULL,
	wrong1 VARCHAR(300) NOT NULL,
	wrong2 VARCHAR(300) NOT NULL,
	wrong3 VARCHAR(300) NOT NULL,
	FOREIGN KEY (exam_ID) REFERENCES Exams(ID),
	PRIMARY KEY (ID)
);